### ISSUE TITLE
Strobing flashes on github.com

### ISSUE THREAD

**Issue by bennypowers** [nt1m/vivaldi-fox#120]
Hello!

I'm a long time user. Thanks for publishing this addon.

I've noticed that on macOS 11.6.1 using Firefox 95.0b3 (64-bit), the browser's color scheme strobes back and forth on github.com.

I notice this in the browser bar, as well as in dev tools, which strobe along with the toolbar.

This only seems to happen on github.com

**Comment by toastal** [comment]
It also really drains battery and spins up my laptop fans

**Comment by toastal** [comment]
If you visit the [Appearance settings](https://github.com/settings/appearance), you can see the day/night themes toggle indefinitely. There are no issues on other git forges, GitLab, Sourcehut, Codeberg, etc.

**Comment by bennypowers** [comment]
Setting "Alternate color source" to anything other than "Favicon" stops the strobing, but also prevents VivaldiFox from working on most other websites

**Comment by nt1m** [comment]
This is an interesting issue:
* Github reacts to `prefers-color-scheme` media query updates and sets the favicon to white/black accordingly (white on dark theme, black on light theme)
* Firefox changes the `prefers-color-scheme` media query value based on the toolbar background (black -> dark, white -> light)

So what ends up happening here is:
* You visit Github
* initially favicon is black
* vivaldifox turns Firefox toolbar background into black to match favicon
* Firefox changes prefers-color-scheme to dark to match Firefox toolbar background
* Github turns favicon to white again (since prefers-color-scheme is now dark)
* Vivaldifox turns Firefox toolbar background into white to match favicon
* Firefox changes prefers-color-scheme to light to match Firefox toolbar background
* Github turns favicon to dark again (since prefers-color-scheme is now light)
* and so on...

A workaround here would be setting `layout.css.prefers-color-scheme.content-override` to `2` in `about:config` to restore former behavior.

Though I think the extension can do that by itself, so I might do that for the next release.

@emilio Do you know if there's something that can be done directly on the Firefox side? I think Firefox shouldn't react to per-window/dynamic theme changes (updates given by `browser.theme.update()`) for prefers-color-scheme imo.

**Comment by nt1m** [comment]
@bennypowers @toastal  This should be fixed when Version 3.2 comes out. Thanks for reporting!

**Comment by toastal** [comment]
@nt1m Awesome. Great work!

That seems really odd to me though. I built a reactive favicon recently and did the `prefers-color-scheme` wholly inside the SVG's `<style>` tag. Are they involving JavaScript where they don't need to?
