### ISSUE TITLE
vivaldi-fox fails to initialize due to "b undefined" in colour.js:43

### ISSUE THREAD

**Issue by riedel** [nt1m/vivaldi-fox#32]
`09:00:19.808 vivaldi-fox:Object { stack: "", 5 more… }|runner.js:166`
and
`09:00:19.809 vivaldi-fox:Object { stack: "", 5 more… }|Promise-backend.js:940`

the output object roughly has the following information

```
    {
    filename: "resource://gre/.../toolkit/loader.js -> resource://vivaldi-fox/utils/colour.js"
    line-number: 43
    message: "b is undefined"
    }

```

strangly it worked before restarting my machine (I am not aware of updates)

Firefox version: 48.0.1
VivaldiFox: 1.2.6

**Comment by riedel** [comment]
Now works again. Depends on open tabs. Seemingly there is more than hex, rgb and rgba possible. Would not be so bad if it failed gracefully, but plugin not running at all.

**Comment by nt1m** [comment]
@riedel Sorry for the very late reply, does this still happen with VivaldiFox 1.2.7 ?

**Comment by Quicksaver** [comment]
@nt1m I believe this happens when starting Firefox with more than one window. If you start with only one window, you can open new windows without fail, but if at startup the restored session has two windows or more, the second window will fail to initialize properly with the error above, and it won't initialize in new windows either apparently.
