### ISSUE TITLE
Colors don't always change when going back/forward

### ISSUE THREAD

**Issue by easyaspi314** [nt1m/vivaldi-fox#37]
Colors don't change when Firefox decides to use a cached copy of the previous web page to go back or forward on. 

Unfortunately, I looked at the API and couldn't find a way to listen for that. :(

**Comment by nt1m** [comment]
Thanks for reporting, unfortunately I can't reproduce this bug, even on a blank profile. Do you have a specific configuration?

**Comment by easyaspi314** [comment]
It only happens when Firefox loads a cached copy.

When you hit Back and it instantly switches and there is no spinner.

Firefox doesn't always do it.

**Comment by nt1m** [comment]
Hmm, I have to repeat back-forward multiple times before firefox loads a cached copy, looks like a rare use-case to me (rare enough that it's been only reported now).

I can't really think of an event that could work in this case, unload doesn't work because the page isn't loaded yet, and the load event isn't emitted in this case :/

**Comment by wsdfhjxc** [comment]
You might want to look into `pageshow` and `pagehide` events which are emitted during regular and cached history navigation. Adding a listener to either of them and updating the color inside should fix the problem.

**Comment by nt1m** [comment]
@wsdfhjxc Nice! `pageshow` seems to be what I'm looking for.

**Comment by easyaspi314** [comment]
@wsdfhjxc Agreed. I was looking in the Firefox SDK. Yet it was just some simple HTML5 JavaScript. :)
